### ISSUE TITLE
new hardware for Smartport 

### ISSUE THREAD

**Issue by jonathan2018** [schwabe/DIY-Multiprotocol-TX-Module#2]
hey @schwabe  
as talk on github Opentx  about Spolling PID .... 
i suggest to make a new hardware for Smartport on Multiprotocol .  i saw on hardware Orginal Frsky use diagram same photo bellow : 
![original_x4rsb_ckt_rep](https://user-images.githubusercontent.com/35451398/50547423-b0472f80-0c6b-11e9-8159-78fbac39b5a6.png)

if use this diagram ,  have to change code ?

**Comment by jonathan2018** [comment]
i availble component to do this . Problem i not yet kill write code

**Comment by schwabe** [comment]
You should bring this to the upstream project. This repo just contains my personal modifcations.
